# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programSource\Qt\calculator\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1003, 726)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(813, 726))
        MainWindow.setMaximumSize(QtCore.QSize(1005, 780))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("nano_icon_pack_6.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.history = QtWidgets.QTextBrowser(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(750, 160, 241, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.history.setFont(font)
        self.history.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.history.setObjectName("history")
        self.inputBox = QtWidgets.QTextEdit(self.centralwidget)
        self.inputBox.setGeometry(QtCore.QRect(10, 10, 731, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(33)
        self.inputBox.setFont(font)
        self.inputBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inputBox.setStatusTip("")
        self.inputBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputBox.setObjectName("inputBox")
        self.pb7 = QtWidgets.QPushButton(self.centralwidget)
        self.pb7.setGeometry(QtCore.QRect(200, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb7.setFont(font)
        self.pb7.setObjectName("pb7")
        self.pb8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb8.setGeometry(QtCore.QRect(310, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb8.setFont(font)
        self.pb8.setObjectName("pb8")
        self.pb9 = QtWidgets.QPushButton(self.centralwidget)
        self.pb9.setGeometry(QtCore.QRect(420, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb9.setFont(font)
        self.pb9.setObjectName("pb9")
        self.pb4 = QtWidgets.QPushButton(self.centralwidget)
        self.pb4.setGeometry(QtCore.QRect(200, 330, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb4.setFont(font)
        self.pb4.setObjectName("pb4")
        self.pb5 = QtWidgets.QPushButton(self.centralwidget)
        self.pb5.setGeometry(QtCore.QRect(310, 330, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb5.setFont(font)
        self.pb5.setObjectName("pb5")
        self.pb6 = QtWidgets.QPushButton(self.centralwidget)
        self.pb6.setGeometry(QtCore.QRect(420, 330, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb6.setFont(font)
        self.pb6.setObjectName("pb6")
        self.pb1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(200, 440, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb1.setFont(font)
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb2.setGeometry(QtCore.QRect(310, 440, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb2.setFont(font)
        self.pb2.setObjectName("pb2")
        self.pb3 = QtWidgets.QPushButton(self.centralwidget)
        self.pb3.setGeometry(QtCore.QRect(420, 440, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb3.setFont(font)
        self.pb3.setObjectName("pb3")
        self.pb0 = QtWidgets.QPushButton(self.centralwidget)
        self.pb0.setGeometry(QtCore.QRect(200, 550, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pb0.setFont(font)
        self.pb0.setObjectName("pb0")
        self.pbDot = QtWidgets.QPushButton(self.centralwidget)
        self.pbDot.setGeometry(QtCore.QRect(420, 550, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbDot.setFont(font)
        self.pbDot.setObjectName("pbDot")
        self.pbEnter = QtWidgets.QPushButton(self.centralwidget)
        self.pbEnter.setGeometry(QtCore.QRect(640, 550, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbEnter.setFont(font)
        self.pbEnter.setObjectName("pbEnter")
        self.pbAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pbAdd.setGeometry(QtCore.QRect(530, 440, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbAdd.setFont(font)
        self.pbAdd.setObjectName("pbAdd")
        self.pbMin = QtWidgets.QPushButton(self.centralwidget)
        self.pbMin.setGeometry(QtCore.QRect(640, 440, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbMin.setFont(font)
        self.pbMin.setObjectName("pbMin")
        self.pbMul = QtWidgets.QPushButton(self.centralwidget)
        self.pbMul.setGeometry(QtCore.QRect(530, 330, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbMul.setFont(font)
        self.pbMul.setObjectName("pbMul")
        self.pbDvd = QtWidgets.QPushButton(self.centralwidget)
        self.pbDvd.setGeometry(QtCore.QRect(640, 330, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbDvd.setFont(font)
        self.pbDvd.setObjectName("pbDvd")
        self.pbPwr = QtWidgets.QPushButton(self.centralwidget)
        self.pbPwr.setGeometry(QtCore.QRect(530, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbPwr.setFont(font)
        self.pbPwr.setObjectName("pbPwr")
        self.pbMod = QtWidgets.QPushButton(self.centralwidget)
        self.pbMod.setGeometry(QtCore.QRect(420, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.pbMod.setFont(font)
        self.pbMod.setObjectName("pbMod")
        self.pbClearHistory = QtWidgets.QPushButton(self.centralwidget)
        self.pbClearHistory.setGeometry(QtCore.QRect(750, 610, 241, 41))
        self.pbClearHistory.setObjectName("pbClearHistory")
        self.pbClear = QtWidgets.QPushButton(self.centralwidget)
        self.pbClear.setGeometry(QtCore.QRect(530, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pbClear.setFont(font)
        self.pbClear.setObjectName("pbClear")
        self.pbDel = QtWidgets.QPushButton(self.centralwidget)
        self.pbDel.setGeometry(QtCore.QRect(640, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.pbDel.setFont(font)
        self.pbDel.setObjectName("pbDel")
        self.pbLkh = QtWidgets.QPushButton(self.centralwidget)
        self.pbLkh.setGeometry(QtCore.QRect(200, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pbLkh.setFont(font)
        self.pbLkh.setObjectName("pbLkh")
        self.pbRkh = QtWidgets.QPushButton(self.centralwidget)
        self.pbRkh.setGeometry(QtCore.QRect(310, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pbRkh.setFont(font)
        self.pbRkh.setObjectName("pbRkh")
        self.pbSqrt = QtWidgets.QPushButton(self.centralwidget)
        self.pbSqrt.setGeometry(QtCore.QRect(640, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(38)
        self.pbSqrt.setFont(font)
        self.pbSqrt.setObjectName("pbSqrt")
        self.pbAns = QtWidgets.QPushButton(self.centralwidget)
        self.pbAns.setGeometry(QtCore.QRect(530, 550, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.pbAns.setFont(font)
        self.pbAns.setObjectName("pbAns")
        self.NDbox = QtWidgets.QTextEdit(self.centralwidget)
        self.NDbox.setGeometry(QtCore.QRect(750, 10, 241, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.NDbox.setFont(font)
        self.NDbox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.NDbox.setObjectName("NDbox")
        self.pbSqr = QtWidgets.QPushButton(self.centralwidget)
        self.pbSqr.setGeometry(QtCore.QRect(110, 160, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbSqr.setFont(font)
        self.pbSqr.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbSqr.setObjectName("pbSqr")
        self.pbSin = QtWidgets.QPushButton(self.centralwidget)
        self.pbSin.setGeometry(QtCore.QRect(10, 160, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbSin.setFont(font)
        self.pbSin.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbSin.setObjectName("pbSin")
        self.pb1Dx = QtWidgets.QPushButton(self.centralwidget)
        self.pb1Dx.setGeometry(QtCore.QRect(110, 240, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb1Dx.setFont(font)
        self.pb1Dx.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pb1Dx.setObjectName("pb1Dx")
        self.pbAbs = QtWidgets.QPushButton(self.centralwidget)
        self.pbAbs.setGeometry(QtCore.QRect(110, 320, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbAbs.setFont(font)
        self.pbAbs.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbAbs.setObjectName("pbAbs")
        self.pbLn = QtWidgets.QPushButton(self.centralwidget)
        self.pbLn.setGeometry(QtCore.QRect(110, 400, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbLn.setFont(font)
        self.pbLn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbLn.setObjectName("pbLn")
        self.pbE = QtWidgets.QPushButton(self.centralwidget)
        self.pbE.setGeometry(QtCore.QRect(110, 480, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.pbE.setFont(font)
        self.pbE.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbE.setObjectName("pbE")
        self.pbPi = QtWidgets.QPushButton(self.centralwidget)
        self.pbPi.setGeometry(QtCore.QRect(110, 560, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.pbPi.setFont(font)
        self.pbPi.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbPi.setObjectName("pbPi")
        self.pbCos = QtWidgets.QPushButton(self.centralwidget)
        self.pbCos.setGeometry(QtCore.QRect(10, 240, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbCos.setFont(font)
        self.pbCos.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbCos.setObjectName("pbCos")
        self.pbTan = QtWidgets.QPushButton(self.centralwidget)
        self.pbTan.setGeometry(QtCore.QRect(10, 320, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbTan.setFont(font)
        self.pbTan.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbTan.setObjectName("pbTan")
        self.pbDegree = QtWidgets.QPushButton(self.centralwidget)
        self.pbDegree.setGeometry(QtCore.QRect(10, 480, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.pbDegree.setFont(font)
        self.pbDegree.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbDegree.setObjectName("pbDegree")
        self.pbI = QtWidgets.QPushButton(self.centralwidget)
        self.pbI.setGeometry(QtCore.QRect(10, 560, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(26)
        self.pbI.setFont(font)
        self.pbI.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbI.setObjectName("pbI")
        self.pbJC = QtWidgets.QPushButton(self.centralwidget)
        self.pbJC.setGeometry(QtCore.QRect(10, 400, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pbJC.setFont(font)
        self.pbJC.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pbJC.setObjectName("pbJC")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 640, 181, 16))
        self.label.setMouseTracking(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.Qexit = QtWidgets.QAction(MainWindow)
        self.Qexit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.Qexit.setObjectName("Qexit")
        self.Qhelp = QtWidgets.QAction(MainWindow)
        self.Qhelp.setObjectName("Qhelp")
        self.Qabout = QtWidgets.QAction(MainWindow)
        self.Qabout.setObjectName("Qabout")
        self.menu.addAction(self.Qexit)
        self.menu_2.addAction(self.Qhelp)
        self.menu_2.addAction(self.Qabout)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.Qexit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "科  学  计  算  器"))
        self.pb7.setText(_translate("MainWindow", "7"))
        self.pb8.setText(_translate("MainWindow", "8"))
        self.pb9.setText(_translate("MainWindow", "9"))
        self.pb4.setText(_translate("MainWindow", "4"))
        self.pb5.setText(_translate("MainWindow", "5"))
        self.pb6.setText(_translate("MainWindow", "6"))
        self.pb1.setText(_translate("MainWindow", "1"))
        self.pb2.setText(_translate("MainWindow", "2"))
        self.pb3.setText(_translate("MainWindow", "3"))
        self.pb0.setText(_translate("MainWindow", "0"))
        self.pbDot.setText(_translate("MainWindow", "."))
        self.pbEnter.setText(_translate("MainWindow", "="))
        self.pbAdd.setText(_translate("MainWindow", "+"))
        self.pbMin.setText(_translate("MainWindow", "-"))
        self.pbMul.setText(_translate("MainWindow", "×"))
        self.pbDvd.setText(_translate("MainWindow", "÷"))
        self.pbPwr.setText(_translate("MainWindow", "^"))
        self.pbMod.setText(_translate("MainWindow", "mod"))
        self.pbClearHistory.setText(_translate("MainWindow", "清空历史区"))
        self.pbClear.setText(_translate("MainWindow", "清空"))
        self.pbDel.setText(_translate("MainWindow", "←"))
        self.pbLkh.setText(_translate("MainWindow", "("))
        self.pbRkh.setText(_translate("MainWindow", ")"))
        self.pbSqrt.setText(_translate("MainWindow", "√"))
        self.pbAns.setText(_translate("MainWindow", "ANS"))
        self.pbSqr.setText(_translate("MainWindow", "▢^2"))
        self.pbSin.setText(_translate("MainWindow", "Sin"))
        self.pb1Dx.setText(_translate("MainWindow", "1/▢"))
        self.pbAbs.setText(_translate("MainWindow", "|▢|"))
        self.pbLn.setText(_translate("MainWindow", "ln(▢)"))
        self.pbE.setText(_translate("MainWindow", "e"))
        self.pbPi.setText(_translate("MainWindow", "π"))
        self.pbCos.setText(_translate("MainWindow", "Cos"))
        self.pbTan.setText(_translate("MainWindow", "Tan"))
        self.pbDegree.setText(_translate("MainWindow", "▢°"))
        self.pbI.setText(_translate("MainWindow", "i"))
        self.pbJC.setText(_translate("MainWindow", "▢!"))
        self.label.setText(_translate("MainWindow", "Sci.calc GUI v3.0"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "计算器"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.Qexit.setText(_translate("MainWindow", "退出"))
        self.Qhelp.setText(_translate("MainWindow", "帮助"))
        self.Qabout.setText(_translate("MainWindow", "关于"))
